services:
  mongo:
    image: mongo:7
    container_name: mongo-rs
    hostname: mongo-rs
    ports:
      - "27018:27017"
    networks:
      - chatai
    volumes:
      - mongo-data:/data/db
    command: ["--replSet", "rs0", "--bind_ip_all"]
    restart: always


volumes:
  mongo-data:

networks:
  chatai:
    external: true